GET http://localhost:3000/users

###

GET http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317

###

POST http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317/saved-products
Content-Type:application/json

{
  "productId": "0d8e554a-84c0-4b9c-bdc3-d04b9bbf1344"
}


###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5",
  "userPreference": {
    "receiveEmail": false
  }
}

###

PATCH http://localhost:3000/users/224f73be-93a6-4cb3-91b1-a837e1e8ec80
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "userPreference": {
    "receiveEmail": true
  }
}

###

DELETE http://localhost:3000/users/e070a68c-6316-40c3-aec2-7848d02fcf93

###

GET http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317/saved-products
